Added login and registration panel, and modified css
hydrogen-oj/hoj-frontend pull request #2
Opened 2020-12-26 03:49 UTC by waterblock79

2020-12-26 15:50 UTC, sparrowhe commented on src/components/Header.vue
> +            window.location.href="/";
字符串使用单引号，操作符左右两边加空格

2020-12-26 15:51 UTC, sparrowhe commented on src/components/Header.vue
> +        if(this.$cookie.getCookie('hoj_username')!=undefined){
操作符左右两边加空格

2020-12-26 15:52 UTC, sparrowhe commented on src/components/Header.vue
> +            window.location.href="/";
跳转不规范，使用vue-route

2020-12-26 15:53 UTC, sparrowhe commented on src/views/Login.vue
> +    p 没有帐号？#[a(href="/register") 注册]
页内跳转不规范 使用vue-router

2020-12-26 15:54 UTC, sparrowhe commented on src/views/Login.vue
> +            const username = document.getElementById("username").value;
这里不应直接访问元素

2020-12-26 15:55 UTC, sparrowhe commented on src/views/Login.vue
> +                    window.location="/";
页内跳转不规范

2020-12-26 15:57 UTC, sparrowhe commented on src/views/Register.vue
> +<template lang="pug">
跳转不规范 我就不挨个点了

2020-12-26 15:58 UTC, sparrowhe requested changes
1. 跳转不规范，应使用vue-router
2. 代码不符合ESLint规范

2020-12-27 04:24 UTC, alexcui03 requested changes
请正确处理分支关系

2020-12-27 04:30 UTC, waterblock79 commented
> 请正确处理分支关系

原先fork仓库删掉了，如果要继续开发只能从版本记录中下载 项目的zip文件，但丢失了原先项目的`.git`文件夹，只能原先文件覆盖最新主分支，求解？

2020-12-29 04:21 UTC, sparrowhe commented on public/index.html
> +    <script src="https://unpkg.com/vue-swal"></script>
不要在index.html里引入其他js，规范使用yarn包管理

2020-12-29 04:22 UTC, sparrowhe requested changes
index.html内不要引入第三方js，规范使用yarn包管理

2020-12-31 01:18 UTC, waterblock79 commented
> 规范使用yarn包管理

关于`规范使用yarn包管理`，请给出需要更改的文件？谢谢

2021-01-02 07:57 UTC, sparrowhe commented
> > 规范使用yarn包管理
> 
> 关于`规范使用yarn包管理`，请给出需要更改的文件？谢谢

index.html文件中不引用第三方包，一律通过yarn管理，webpack统一打包

2021-01-15 04:41 UTC, sparrowhe approved these changes

2021-01-15 04:42 UTC, merged